### ISSUE TITLE
Minify CSS and JS

### ISSUE THREAD

**Issue by virus-warnning** [virus-warnning/RenderTheFuck#7]
### Tasks
* [x] Update package.json
* * [x] Config uglify
* * [x] Config cssmin
* [x] Remove hard coded inline CSS
* [x] Load CSS resource at hook point
* [x] Apply minified version

### References
* [UglifyJS2](https://github.com/mishoo/UglifyJS2)
* [cssmin](https://github.com/jbleuzen/node-cssmin)
